name: release
on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0

      - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1
        with:
          components: rustfmt, clippy
          cache: false

      - uses: MarcoIeni/release-plz-action@b86d133974cdeac8c9e79a76a6b5b70fc77d0826 # v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.RPLZ_GITHUB_PAT }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.RPLZ_CARGO_REGISTRY_TOKEN }}
        with:
          config: .github/release-plz.toml
          command: release

  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0

      - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1
        with:
          components: rustfmt, clippy
          cache: false

      - uses: MarcoIeni/release-plz-action@b86d133974cdeac8c9e79a76a6b5b70fc77d0826 # v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.RPLZ_GITHUB_PAT }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.RPLZ_CARGO_REGISTRY_TOKEN }}
        with:
          config: .github/release-plz.toml
          command: release-pr
